
schemaName: sharding_db

dataSourceCommon:
 username: root
 password: mysqlstart
 connectionTimeoutMilliseconds: 30000
 idleTimeoutMilliseconds: 60000
 maxLifetimeMilliseconds: 1800000
 maxPoolSize: 5
 minPoolSize: 1
 maintenanceIntervalMilliseconds: 30000

dataSources:
 ds_0:
   url: jdbc:mysql://127.0.0.1:3306/mall_ds_0?serverTimezone=UTC&useSSL=false
 ds_1:
   url: jdbc:mysql://127.0.0.1:3306/mall_ds_1?serverTimezone=UTC&useSSL=false

rules:
- !SHARDING
 tables:
   order_info:
     actualDataNodes: ds_${0..1}.order_info_${0..15}
     tableStrategy:
       standard:
         shardingColumn: order_id
         shardingAlgorithmName: order_info_inline
     keyGenerateStrategy:
       column: order_id
       keyGeneratorName: snowflake
 bindingTables:
   - order_info
 defaultDatabaseStrategy:
   standard:
     shardingColumn: user_id
     shardingAlgorithmName: database_inline
 defaultTableStrategy:
   none:
 
 shardingAlgorithms:
   database_inline:
     type: INLINE
     props:
       algorithm-expression: ds_${user_id % 2}
   order_info_inline:
     type: INLINE
     props:
       algorithm-expression: order_info_${order_id % 16}

 
 keyGenerators:
   snowflake:
     type: SNOWFLAKE
     props:
       worker-id: 123
